image: node:11

before_script:
  - npm install
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - mkdir -p ~/.ssh
  - eval $(ssh-agent -s)
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

cache:
  paths:
    - node_modules/

test:lint:
  script:
    - npm run lint

push-to-ec2:
    stage: deploy
    script:     
      - npm run build
      - ssh-add <(echo "$SSH_PRIVATE_KEY")
      - ssh ubuntu@$DEPLOY_SERVER "rm -rf /var/www/html/$APACHE_SUBDIR/*"
      - scp -r dist/* ubuntu@$DEPLOY_SERVER:/var/www/html/$APACHE_SUBDIR"
