image: node:11

before_script:
  - npm install

cache:
  paths:
    - node_modules/

test:lint:
  script:
    - npm run lint

push-to-ec2:
    stage: deploy
    script:     
      - npm run build
      - ssh-add <(echo "$SSH_PRIVATE_KEY")
      - ssh ubuntu@$DEPLOY_SERVER "rm -rf /var/www/html/$APACHE_SUBDIR/*"
      - scp -r dist/* ubuntu@$DEPLOY_SERVER:/var/www/html/$APACHE_SUBDIR"
